---
- name: Deploy Game Store App using Docker Compose
  hosts: all
  become: yes
  vars:
    app_dir: /opt/game-store
    local_compose_file: ../docker/docker-compose.yml

  tasks:
    - name: Ensure application directory exists on remote
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml from local ../docker directory to remote
      copy:
        src: "{{ local_compose_file }}"
        dest: "{{ app_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Pull Docker images
      command: docker compose pull
      args:
        chdir: "{{ app_dir }}"

    - name: Start containers with Docker Compose
      command: docker compose up -d
      args:
        chdir: "{{ app_dir }}"

    - name: Show running containers
      command: docker ps
