---
- name: Configure Nginx as reverse proxy
  hosts: game_store_servers
  become: yes
  
  vars:
    nginx_config_file: /etc/nginx/sites-available/game-store
    nginx_enabled_file: /etc/nginx/sites-enabled/game-store
    
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present
        
    - name: Create Nginx configuration
      copy:
        content: |
          server {
              listen 80;
              server_name _;
              
              # Serve frontend
              location / {
                  proxy_pass http://localhost:5003;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
              
              # Proxy backend API requests
              location /api/ {
                  proxy_pass http://localhost:5274;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        dest: "{{ nginx_config_file }}"
        
    - name: Enable Nginx site configuration
      file:
        src: "{{ nginx_config_file }}"
        dest: "{{ nginx_enabled_file }}"
        state: link
      notify: Restart Nginx
      
    - name: Ensure Nginx service is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
        
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted